### ISSUE TITLE
ObjectId validation

### ISSUE THREAD

**Issue by pyrsmk** [elbywan/bson.cr#3]
Hello 👋

It would be nice to have a validator for ObjectIds. I am currently in need to validate keys before creating a new ObjectId because I am loading unsafe data from XML files (used for interfacing two services). Adding the validation process into the constructor would be less performant and not really needed for the major number of use cases. So here's my proposal (currently a nasty monkey patch):

```crystal
struct BSON
  struct ObjectId
    def self.validate(id : String) : Bool
      !!(id =~ /[a-z0-9]{24}/)
    end
  end
end
```

This probably can be optimized (by using anything else but a regex) and I don't know if the implementation is really robust, but it seemed to me that checking the length and the characters was enough by itself.

What are your thoughts ?

Of course, I'm available to push a PR.

**Comment by elbywan** [comment]
Hey @pyrsmk,

> What are your thoughts ?

Adding a validator method would be nice indeed!

Regarding the implementation, I think that we can change the regex part to something like:

```crystal
def self.validate(id : String) : Bool
  id.hexbytes?.try &.size == 12
end
```

> Of course, I'm available to push a PR.

Thanks! 👍

**Comment by pyrsmk** [comment]
Way better indeed, I'll push a PR !
